[package]
name = "tcplay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = { version = "1.0.0", features = ["tokio"] }
pnet = "0.33.0"
