[package]
name = "picaplay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "picaplay"
path = "src/lib.rs"


[dependencies]
pcap = { version = "2.2.0", features = ["tokio"] }
pnet = "0.35.0"
